/*
 * Panel de la lista
 */
package vista;

import controlador.MyList;
import controlador.MyList.Node;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author Di Qi
 */
public class PanelLista extends javax.swing.JPanel {
    
    private App app;
    private MyList<Empleado> lista;

    /**
     * Creates new form PanelLista
     */
    public PanelLista(App app, MyList<Empleado> lista) {
        initComponents();
        
        this.app = app;
        this.lista = lista;
        
        actualizarLista();
    }
    
    public void actualizarLista() {
        DefaultListModel modelo = new DefaultListModel();
        Node aux = this.lista.getFirstNode();
        
        while(aux != null) {
            modelo.addElement(aux.getMain());
            
            aux = aux.getNextNode();
        }
        
        jListEmpleados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        btnSeleccionar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(438, 438));
        setMinimumSize(new java.awt.Dimension(438, 438));
        setPreferredSize(new java.awt.Dimension(438, 438));

        jListEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(jListEmpleados);

        btnSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSeleccionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int index = jListEmpleados.getSelectedIndex();
        
        if (index != -1) {
            Empleado e = jListEmpleados.getSelectedValue();
            PanelUnoAUno p = this.app.getPanelUnoUno();
            
            this.lista.setActualNode(this.lista.getNode(e.getNumero()));
            p.actualizarVista();
            
            this.app.setPanelUnoAUno();
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado.");
        }
        
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JList<Empleado> jListEmpleados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
